# Generated by Django 4.1.7 on 2023-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_userpokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='userpokemon',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.pokemon'),
        ),
    ]
