# Generated by Django 4.1.7 on 2023-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_remove_userpokemon_pokemon_userpokemon_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
