# Generated by Django 4.1.7 on 2023-03-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
    ]
