# Generated by Django 4.1.7 on 2023-03-19 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0008_remove_pokemon_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='pokemon',
        ),
        migrations.CreateModel(
            name='CapturedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='userpokemon',
            name='captured_pokemon',
            field=models.ManyToManyField(to='pokemon.capturedpokemon'),
        ),
    ]
