# Generated by Django 4.1.7 on 2023-03-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_remove_userpokemon_pokemon_capturedpokemon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='captured_pokemon',
        ),
        migrations.DeleteModel(
            name='CapturedPokemon',
        ),
    ]
