# Generated by Django 4.1.7 on 2023-03-19 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0010_remove_userpokemon_captured_pokemon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('captured_date', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='userpokemon',
            name='captured_pokemon',
            field=models.ManyToManyField(limit_choices_to={'captured_by': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, to='pokemon.capturedpokemon'),
        ),
    ]
