# Generated by Django 4.1.7 on 2023-03-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_capturedpokemon_userpokemon_captured_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='captured_pokemon',
            field=models.ManyToManyField(blank=True, related_name='captured_by_users', to='pokemon.capturedpokemon'),
        ),
    ]
