# Generated by Django 4.1.7 on 2023-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_alter_userpokemon_captured_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='captured_pokemon',
        ),
        migrations.AddField(
            model_name='userpokemon',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.pokemon'),
        ),
        migrations.DeleteModel(
            name='CapturedPokemon',
        ),
    ]
