# Generated by Django 4.1.7 on 2023-03-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_capturedpokemons_delete_capturedpokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.capturedpokemons'),
        ),
    ]
