# Generated by Django 4.1.7 on 2023-03-19 10:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_alter_userpokemon_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpokemon',
            name='pokemon',
            field=models.ManyToManyField(limit_choices_to={'user__id': django.db.models.expressions.OuterRef('user_id')}, related_name='user_pokemons', to='pokemon.capturedpokemons'),
        ),
    ]
