# Generated by Django 4.1.7 on 2023-03-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0019_alter_userpokemon_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpokemon',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='userpokemon',
            name='user',
        ),
        migrations.DeleteModel(
            name='CapturedPokemons',
        ),
        migrations.DeleteModel(
            name='UserPokemon',
        ),
    ]
